baseURL: https://imkerei.brunnhaus.de/
languageCode: en-us
title: Imkerei Brunnhaus
theme: hugo-fresh
disableKinds:
- taxonomy
- taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: false

params:
  openGraph: false
  # Used as meta data; describe your site to make Google Bots happy 
  description: Leckere Honige und Bienenwachsprodukte von der Imkerei Brunnhaus im Isartal
  navbarlogo:
    image: logos/logo_wide.png
    link: /
  font:
    name: "Open Sans"
    sizes: [400,600]
  hero:
    title: Imkerei Brunnhaus - Honig aus dem Isartal
    # subtitle: "Verschiedene Honigsorten aus dem Isartal: Super Sommer, Fetter Frühling, Honig Trip, ..."
    subtitle: 
    - line: "Gutes aus dem Isartal: der Super Sommer Honig ist jetzt verfügbar"
    - line: "außerdem haben wir [Holzbutter](#products) und auch [Kussbutter](#products)!"
    image: favicon.png
    clientlogos:
      - supersommer_deckel
      - honigtrip_deckel
      - sommerbär_deckel
      - fetterfrühling_deckel
      - frühlingsbär_deckel
  # Customizable navbar. For a dropdown, add a "sublinks" list.
  navbar:
  - title: Honigsorten
    url: "/#sorten"
  - title: Informationen
    url: "/#info"
  - title: Produkte
    url: "/#products"
    sublinks:
    - title: Holzbutter
      url: "/#holzbutter"
    - title: Kussbutter
      url: "/#kussbutter"
  - title: Eindrücke
    url: "/#impressions"
    sublinks:
    - title: Bilder
      url: "/#impressions"
    - title: Kommentare
      url: "/#comments"
  - title: Kontakt
    url: "/#form"
    button: true
  section1:
    title: Honigsorten
    subtitle: Der leckere Honig aus dem Isartal mit den coolsten Etiketten
    tiles:
    - title: Super Sommer '21
      icon: supersommer
      text: Linde, Kreuzblütler, Himbeere, Wegerich, Mädesüß, Lavendel, Eiche, Süßgräser
      message: Jetzt auf Lager
      color: green
    - title: Honig Trip '20
      icon: honigtrip 
      text: Raps, Weide, Obst, Ahorn, Himbeere
      message: Ausverkauft
      color: orange
    - title: Sommer Bär '19
      icon: sommerbär
      text: Imker R. Seidl
      color: orange
      message: Ausverkauft
    - title: Frühlings Bär '19
      icon: frühlingsbär
      text: Imker R. Seidl
      message: Ausverkauft
      color: orange
    # - title: Super Sommer '19
    #   icon: supersommer
    #   text: Linde, Himbeere, Kreuzblütler, Obst, Klee, Natterkopf, Roßkastanie, Wein
    #   message: Ausverkauft
    - title: Fetter Frühling '19
      icon: fetterfrühling
      text: Raps, Himbeere, Roßkastanie, Hartriegel, Hornklee, Linde, Ahorn
      message: Ausverkauft
      color: orange
  section2:
    title: Unser Isartal Honig
    subtitle: Imkerei Brunnhaus
    features:
    - title: Kontakt
      text: "Imker Dr. Ditmar Unger, [An der Isar 2, 82049 Pullach im Isartal.](https://google.de/search?q=Imkerei+Brunnhaus) Für Fragen und Anregungen bitte das Formular am Ende der Webseite nutzen."
      icon: map-marker
    - title: Direkt in der Natur
      text:  'Direkt am 300 Jahre alten, ehemalig "Königlichen Hofbrunnhaus an der Isar" stehen meine Buckfast Bienenstöcke im FFH Gebiet Isarauen unterhalb vom Biergarten Waldwirtschaft.'
      icon: beehive-outline
    - title: Naturbelassen
      text: 'Ungespritzte und vielfältige Pollen- und Nektarquellen stehen so meinen Bienen über das Jahr zur Verfügung wie z. B. Weide, Märzenbecher, Weißdorn, Kirschpflaume, Kirsche, Apfel, Felsenbirne, Löwenzahn, Roßkastanie, Linde, Natterkopf, Alpenclematis, Wildrosen und viele Wildblumen am Ufer der Isar.'
      icon: flower-outline
    - title: Überwachung
      icon: chart-areaspline
      text: Unsere Bienenstöcke werden mit Hilfe modernster Technologie überwacht
      image:
      - name: delta
      - name: humid
  section3:
    items:
    - title: Gute Holzbutter
      subtitle: "Das Beste was Du Deinem Holz antun kannst (finden wir). Aus 100% Leinöl und Bienenwachs von unseren Bienen! Für Dein Schneidebrett, Tisch, Messergriff, Möbel, usw."
      image: holzbutter.jpg
      anchor: holzbutter
    - title: Gute Kussbutter
      subtitle: "Lippenbalsam aus Kokosöl, Bienenwachs und Honig mit Propolis und ein paar Tropfen Kamilleextrakt oder Teebaumöl in schönem Holzdöschen aus Mirabelle oder Kirschpflaume."
      image: kussbutter.jpg
      anchor: kussbutter
  section4:
    title: Ein paar Eindrücke
    subtitle: von unserer Imkerei
    images:
    - name: supersommer_nah.jpg
    - name: kästen.jpg
    - name: supersommer.jpg
    clients:
    - name: Wolf
      quote: "Samstag Morgen, graue Wolken – trübe Stimmung? Weg damit! Dr. Ditmar Ungers Super Sommer Isartal-Honig bringt neue Spannkraft und Lebensfreude. Quellfrisch und goldgelb aus der Imkerei Brunnhaus im lieblichen Isartal. Jetzt probieren. Für jeden Tag! Und der Super Sommer kommt zurück."
      job: Grafikdesigner
      img: sheep.jpg
    - name: Christoph
      quote: "Spitzen Honig aus einer wunderschönen Gegend vom Imker mit viel Einfallsreichtum, Geschick und gutem Händchen. Unser neuer Haushonig und Hofimker!"
      job: Hacker
      img: h.jpg
    - name: Ditmar
      quote: "Es gibt wieder Sommerhonig - flüssig und cremig gerührt - sowie Holz- und Kussbutter!"
      job: Hobbyimker
      img: d.jpg
  section5:
    enabled: true
    lists:
    - name: Honig Verfügbarkeit
      idHtml: 68a8e
      idDb: 68a8e4a9-1086-42de-ac0d-20c5065cd089
    - name: Weitere Produkte
      idHtml: 9a7be
      idDb: 9a7bef05-f7c0-43c8-8fdd-27a56b8daa15
  footer:
    logo: logo_small.png
    socialmediatitle: Folge uns
    socialmedia:
    - link: https://google.de/search?q=Imkerei+Brunnhaus
      icon: google
    - link: https://gitlab.com/brunnhaus
      icon: git
    quicklinks:
      column1:
        title: Impressum
        links:
        - text: Imker - Dr. Ditmar Unger
          link: https://brunnhaus.de
        - text: "Mehr Bilder und auch Postkarten von meinem Sohn Julian"
          link: https://julianlauer.de
        - text: "Webseite von meinem Sohn Janek"
          link: https://github.com/schlauerlauer/
        - text: "⠀"
        - text: Bienenstock Metriken in Grafana
          link: https://monitoring.brunnhaus.de/d/bienen/bienen
        - text: "⠀"
        - text: "No cookies found 🤷‍♀️ have this one 🍪"
          link: https://gitlab.com/brunnhaus/honig