baseURL: https://honig.brunnhaus.de/
languageCode: en-us
title: Imkerei Brunnhaus
theme: hugo-fresh
disableKinds:
- taxonomy
- taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: false

params:
  openGraph: false
  # Used as meta data; describe your site to make Google Bots happy 
  description: Leckere Honige und Bienenwachsprodukte von der Imkerei Brunnhaus im Isartal
  navbarlogo:
    image: logos/logo_wide.png
    link: /
  font:
    name: "Open Sans"
    sizes: [400,600]
  hero:
    title: Imkerei Brunnhaus
    # subtitle: "Verschiedene Honigsorten aus dem Isartal: Super Sommer, Fetter Frühling, Honig Trip, ..."
    subtitle: 
    - line: "Gutes aus dem Isartal: der Honig von 2020 ist leider bereits ausverkauft"
    - line: "aber wir haben jetzt [Holzbutter](#products) und neu auch [Kussbutter](#products)!"
    image: favicon.jpg
    clientlogos:
      - supersommer_deckel
      - honigtrip_deckel
      - sommerbär_deckel
      - fetterfrühling_deckel
      - frühlingsbär_deckel
  # Customizable navbar. For a dropdown, add a "sublinks" list.
  navbar:
  - title: Honigsorten
    url: "/#sorten"
  - title: Informationen
    url: "/#info"
  - title: Produkte
    url: "/#products"
    sublinks:
    - title: Holzbutter
      url: "/#holzbutter"
    - title: Kussbutter
      url: "/#kussbutter"
  - title: Eindrücke
    url: "/#impressions"
    sublinks:
    - title: Bilder
      url: "/#impressions"
    - title: Kommentare
      url: "/#comments"
  - title: Kontakt
    url: "/#form"
    button: true
  section1:
    title: Honigsorten
    subtitle: Der leckere Honig aus dem Isartal mit den coolsten Etiketten
    tiles:
    - title: Super Sommer '20
      icon: supersommer
      text: Linde, Kreuzblütler, Himbeere, Wegerich, Mädesüß, Lavendel, Eiche, Süßgräser
      message: Leider bereits ausverkauft 
    - title: Honig Trip '20
      icon: honigtrip 
      text: Raps, Weide, Obst, Ahorn, Himbeere
      message: Ausverkauft
    - title: Sommer Bär '19
      icon: sommerbär
      text: Imker R. Seidl
      message: Ausverkauft
    - title: Frühlings Bär '19
      icon: frühlingsbär
      text: Imker R. Seidl
      message: Ausverkauft
    - title: Super Sommer '19
      icon: supersommer
      text: Linde, Himbeere, Kreuzblütler, Obst, Klee, Natterkopf, Roßkastanie, Wein
      message: Ausverkauft
    - title: Fetter Frühling '19
      icon: fetterfrühling
      text: Raps, Himbeere, Roßkastanie, Hartriegel, Hornklee, Linde, Ahorn
      message: Ausverkauft
  section2:
    title: Unser Isartal Honig
    subtitle: Imkerei Brunnhaus
    features:
    - title: Kontakt
      text: "Imker Dr. Ditmar Unger, [An der Isar 2, 82049 Pullach im Isartal.](https://google.de/search?q=Imkerei+Brunnhaus) Für Fragen und Anregungen bitte das Formular am Ende der Webseite nutzen."
      icon: map-marker
    - title: Direkt in der Natur
      text:  'Direkt am 300 Jahre alten, ehemalig "Königlichen Hofbrunnhaus an der Isar" stehen meine Buckfast Bienenstöcke im FFH Gebiet Isarauen unterhalb vom Biergarten Waldwirtschaft.'
      icon: beehive-outline
    - title: Naturbelassen
      text: 'Ungespritzte und vielfältige Pollen- und Nektarquellen stehen so meinen Bienen über das Jahr zur Verfügung wie z. B. Weide, Märzenbecher, Weißdorn, Kirschpflaume, Kirsche, Apfel, Felsenbirne, Löwenzahn, Roßkastanie, Linde, Natterkopf, Alpenclematis, Wildrosen und viele Wildblumen am Ufer der Isar.'
      icon: flower-outline
    - title: Überwachung
      icon: chart-areaspline
      text: Unsere Bienenstöcke werden mit Hilfe modernster Technologie überwacht
      image:
      - name: graph
      - name: uptime
  section3:
    items:
    - title: Gute Holzbutter
      subtitle: "Das Beste was Du Deinem Holz antun kannst (finden wir). Aus 100% Leinöl und Bienenwachs von unseren Bienen! Für Dein Schneidebrett, Tisch, Messergriff, Möbel, usw."
      image: holzbutter.jpg
      anchor: holzbutter
    - title: Gute Kussbutter
      subtitle: "Lippenbalsam aus Kokosöl, Bienenwachs und Honig mit Propolis und ein paar Tropfen Kamilleextrakt oder Teebaumöl in schönem Holzdöschen aus Mirabelle oder Kirschpflaume."
      image: kussbutter.jpg
      anchor: kussbutter
  section4:
    title: Ein paar Eindrücke
    subtitle: von unserer Imkerei
    images:
    - name: supersommer.jpg
    - name: kästen.jpg
    - name: supersommer_nah.jpg
    clients:
    - name: Wolf
      quote: "Samstag Morgen, graue Wolken – trübe Stimmung? Weg damit! Dr. Ditmar Ungers Super Sommer Isartal-Honig bringt neue Spannkraft und Lebensfreude. Quellfrisch und goldgelb aus der Imkerei Brunnhaus im lieblichen Isartal. Jetzt probieren. Für jeden Tag! Und der Super Sommer kommt zurück."
      job: Grafikdesigner
      img: sheep.jpg
    - name: Christoph
      quote: "Spitzen Honig aus einer wunderschönen Gegend vom Imker mit viel Einfallsreichtum, Geschick und gutem Händchen. Unser neuer Haushonig und Hofimker!"
      job: Hacker
      img: h.jpg
    - name: Ditmar
      quote: "Leider ist der Honig bereits ausverkauft. Wenn Du uns unten eine Nachricht schickst, können wir Dir schreiben, wenn wieder welcher da ist!"
      job: Hobbyimker
      img: d.jpg
  section5: true
  footer:
    logo: logo_small.png
    socialmediatitle: Folge uns
    socialmedia:
    - link: https://google.de/search?q=Imkerei+Brunnhaus
      icon: google
    - link: https://gitlab.com/brunnhaus
      icon: git
    quicklinks:
      column1:
        title: Impressum
        links:
        - text: Imker - Dr. Ditmar Unger
          link: https://brunnhaus.de
        - text: "Etiketten & Logos - Julian Lauer"
          link: https://julianlauer.de
        - text: "Webseite - Janek Lauer"
          link: https://schlauerlauer.de
        - text: "⠀"
        - text: Bienenstock Metriken in Grafana
          link: https://bienen.brunnhaus.de